---
apiVersion: v1
kind: Service
metadata:
  name: svc-docxletters
  labels:
    app: svc-docxletters
spec:
  selector:
    app: docxletters
  ports:
  - port: 8004
    protocol: TCP
    nodePort: 30061
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: docxletters
  template:
    metadata:
      labels:
        app: docxletters
    spec:
      containers:
      - name: docx
        image: migutak/docxletters:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
        volumeMounts:
        - name: vol
          mountPath: /app/nfsmount/demandletters/
        env:
        - name: FILEPATH
          valueFrom:
            configMapKeyRef:
              name: ecol-configmap
              key: FILEPATH
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: docx-pvc
