version: "3.3"
services:
  docxletters:
    image: migutak/docxletters:1.0.0
    container_name: docx
    restart: always
    volumes:
      - /home/ecollectadmin/demandletters/:/app/demands/
    environment:
      - FILEPATH=/app/demands/
    ports:
      - "8004:8004"
