FROM node:10

# Create app directory
RUN mkdir -p /app
RUN mkdir -p /app/demands
WORKDIR /app

#install pm2
RUN npm install pm2 -g

# Install app dependencies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 8004
CMD [ "pm2-runtime", "index.js" ]