FROM node:10 AS appbuild

# Create app directory
RUN mkdir -p /app
RUN mkdir -p /app/nfs/demandletters
RUN mkdir -p /app/docxletters
WORKDIR /app/docxletters

COPY . .

FROM node:10.15.2-alpine
RUN mkdir -p /app
RUN mkdir -p /app/nfs/demandletters
RUN mkdir -p /app/docxletters
WORKDIR /app/docxletters

COPY --from=appbuild /app/docxletters /app/docxletters
EXPOSE 8004

CMD ["node", "index.js"]

#  docker build -t 52.117.54.217:5000/docxletters:1.0.0 .

