version: "3.3"
services:
  docxletters:
    image: migutak/docxletters:1.0.0
    container_name: docx
    restart: always
    volumes:
      - /app/nfsmount/demandletters/:/app/nfsmount/demandletters/
    environment:
      - FILEPATH=/app/nfsmount/demandletters/
      - IMAGEPATH=/app/docxletters/routes/
    ports:
      - "8004:8004"
