apiVersion: v1
kind: Service
metadata:
  name: svc-docxletters
  labels:
    app: svc-docxletters
spec:
  selector:
    app: docxletters
  ports:
  - port: 8004
    protocol: TCP
    nodePort: 30061
  type: NodePort